package enums;
public  enum Raza {
    PASTOR_ALEMAN, BULLDOG, CHIHUAHUA, PASTOR_AUSTRALIANO, PUG, GOLDEN_RETRIEVER, BEAGLE, BULL_TERRIER, BOXER, DACHSHUND, DOBERMAN, HUSKY, LAB, GATO_PERRO, PERRO_GATO, PERRO_PERRO, PERRO_PERRO_PERRO
    
}
